version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0
  maven: circleci/maven@1.3

executors:
  openjdk17:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      JAVA_HOME: /usr/local/openjdk-17
    steps:
      - checkout
      - run:
          name: Set Java version to 17
          command: echo 'export JAVA_HOME=/usr/local/openjdk-17' >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Build project
          command: mvn clean install

  test:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      JAVA_HOME: /usr/local/openjdk-17
    steps:
      - checkout
      - run:
          name: Set Java version to 17
          command: echo 'export JAVA_HOME=/usr/local/openjdk-17' >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Run tests
          command: mvn test

  deploy_heroku:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      JAVA_HOME: /usr/local/openjdk-17
    steps:
      - checkout
      - heroku/install
      - run:
          name: Set Java version to 17
          command: echo 'export JAVA_HOME=/usr/local/openjdk-17' >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a your-heroku-app
            heroku container:release web -a your-heroku-app

workflows:
  my_cicd_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_heroku:
          requires:
            - test
          filters:
            branches:
              only: master
