version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

jobs:
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: dakshajaan/education-space
      SNYK_TOKEN: $SNYK_TOKEN
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $projectm4 .
      - snyk/scan:
          docker-image-name: $projectm4

  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Installing dependencies..." && npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Running tests..." && npm run test

  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: dakshajaan/educational-space
      - docker/push:
          image: dakshajaan/educational-space

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a dakshajaan-su-devops
            heroku container:release web -a dakshajaan-su-devops

workflows:
  version: 2
  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      - scan:
          requires:
            - build
          filters:
            branches:
              only: main
      - publish:
          requires:
            - test
          filters:
            branches:
              only: release
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: release
