version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0
  maven: circleci/maven@1.3

executors:
  openjdk17:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  my_job:
    docker:
      - image: cimg/openjdk:17.0 # Use any image that includes Java
    steps:
      - checkout

  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Set up JDK 17
          command: |
            export JAVA_HOME=/usr/local/openjdk-17
            echo 'export JAVA_HOME=/usr/local/openjdk-17' >> $BASH_ENV
            export PATH=$JAVA_HOME/bin:$PATH
      - run:
          name: Build project
          command: mvn clean install

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Set up JDK 17
          command: |
            export JAVA_HOME=/usr/local/openjdk-17
            echo 'export JAVA_HOME=/usr/local/openjdk-17' >> $BASH_ENV
            export PATH=$JAVA_HOME/bin:$PATH
      - run:
          name: Run tests
          command: mvn test

  deploy_heroku:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Set up JDK 17
          command: |
            export JAVA_HOME=/usr/local/openjdk-17
            echo 'export JAVA_HOME=/usr/local/openjdk-17' >> $BASH_ENV
            export PATH=$JAVA_HOME/bin:$PATH
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a your-heroku-app
            heroku container:release web -a your-heroku-app

workflows:
  my_cicd_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_heroku:
          requires:
            - test
          filters:
            branches:
              only: master
