version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  scan:
    docker:
      - image: openjdk:17-oracle
    environment:
      SNYK_TOKEN: $SNYK_TOKEN
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get update && apt-get install -y maven
      - run:
          name: Build Spring Boot project
          command: mvn clean install

workflows:
  version: 2
  cicd_flow:
    jobs:
      - scan:
          filters:
            branches:
              only: main
